include(main)
include(stm32f4)
include(stm32h7)

set(CHIBIOS_DIR "${MAIN_LIB_DIR}/main/ChibiOS")

set(CHIBIOS_STARTUP_DIR "${CHIBIOS_DIR}/os/common/startup/ARMCMx/compilers/GCC")
set(CHIBIOS_HAL_DIR "${CHIBIOS_DIR}/os/hal")

set(CHIBIOS_F4_STARTUP_DIR "${CHIBIOS_DIR}/os/common/startup/ARMCMx/devices/STM32F4xx")
set(CHIBIOS_F4_HAL_DIR "${CHIBIOS_DIR}/os/hal/ports/STM32/STM32F4xx")

set(CHIBIOS_H7_STARTUP_DIR "${CHIBIOS_DIR}/os/common/startup/ARMCMx/devices/STM32H7xx")
set(CHIBIOS_H7_HAL_DIR "${CHIBIOS_DIR}/os/hal/ports/STM32/STM32H7xx")

set(CHIBIOS_HAL_LLD_DIR "${CHIBIOS_DIR}/os/hal/ports/STM32/LLD")
set(CHIBIOS_HAL_PORT_DIR "${CHIBIOS_DIR}/os/hal/ports/common/ARMCMx")
set(CHIBIOS_HAL_INC_DIR "${CHIBIOS_DIR}/os/hal/include")
set(CHIBIOS_OSAL_DIR "${CHIBIOS_DIR}/os/hal/osal/rt-nil")
set(CHIBIOS_RT_DIR "${CHIBIOS_DIR}/os/rt")
set(CHIBIOS_PORT_DIR "${CHIBIOS_DIR}/os/common/ports/ARMCMx")

file(GLOB_RECURSE CHIBIOS_HAL_LLD_TIM_SRC ${CHIBIOS_HAL_LLD_DIR}/TIMv1/*.c)
file(GLOB_RECURSE CHIBIOS_HAL_PORT_SRC ${CHIBIOS_HAL_PORT_DIR}/*.c)

file(GLOB_RECURSE CHIBIOS_F4_HAL_SRC ${CHIBIOS_F4_HAL_DIR}/*.c)
file(GLOB_RECURSE CHIBIOS_H7_HAL_SRC ${CHIBIOS_H7_HAL_DIR}/*.c)

file(GLOB_RECURSE CHIBIOS_OSAL_SRC ${CHIBIOS_OSAL_DIR}/*.c)
file(GLOB_RECURSE CHIBIOS_RT_SRC ${CHIBIOS_RT_DIR}/src/*.c)

set(CHIBIOS_PORT_SRC
    "${CHIBIOS_PORT_DIR}/chcore.c"
    "${CHIBIOS_PORT_DIR}/chcore_v7m.c"
    "${CHIBIOS_PORT_DIR}/compilers/GCC/chcoreasm_v7m.S"
)

set(CHIBIOS_INCLUDE_DIRS
    "${CHIBIOS_HAL_LLD_DIR}/TIMv1"
    "${CHIBIOS_HAL_LLD_DIR}/EXTIv1"
    "${CHIBIOS_HAL_LLD_DIR}/DMAv2"
    "${CHIBIOS_HAL_LLD_DIR}/RTCv2"
    "${CHIBIOS_HAL_PORT_DIR}"
    "${CHIBIOS_HAL_INC_DIR}"
    "${CHIBIOS_OSAL_DIR}"
    "${CHIBIOS_RT_DIR}/include"
    "${CHIBIOS_PORT_DIR}"
    "${CHIBIOS_PORT_DIR}/compilers/GCC"
    "${CHIBIOS_DIR}/os/license"
    "${CHIBIOS_DIR}/os/oslib/include"
)

set(CHIBIOS_F4_INCLUDE_DIRS
    "${CHIBIOS_F4_STARTUP_DIR}"
    "${CHIBIOS_F4_HAL_DIR}"
)

set(CHIBIOS_H7_INCLUDE_DIRS
    "${CHIBIOS_H7_STARTUP_DIR}"
    "${CHIBIOS_H7_HAL_DIR}"
    "${CHIBIOS_HAL_LLD_DIR}/BDMAv1"
)

set(CHIBIOS_SRC
    "${CHIBIOS_STARTUP_DIR}/crt0_v7m.S"
    "${CHIBIOS_STARTUP_DIR}/crt1.c"
    "${CHIBIOS_DIR}/os/hal/src/hal_st.c"
    "${CHIBIOS_HAL_DIR}/src/hal.c"
    "${CHIBIOS_HAL_LLD_TIM_SRC}"
    "${CHIBIOS_HAL_LLD_DIR}/EXTIv1/stm32_exti.c"
    "${CHIBIOS_HAL_LLD_DIR}/DMAv2/stm32_dma.c"
    "${CHIBIOS_HAL_LLD_DIR}/RTCv2/hal_rtc_lld.c"
    "${CHIBIOS_HAL_PORT_SRC}"
    "${CHIBIOS_OSAL_SRC}"
    "${CHIBIOS_RT_SRC}"
    "${CHIBIOS_PORT_SRC}"
)

set(BRAINFPV_DIR "${MAIN_SRC_DIR}/brainfpv")
file(GLOB_RECURSE BRAINFPV_INAV_SRC ${BRAINFPV_DIR}/*.c)


set(BRAINFPV_F4_INCLUDE_DIRS
    "${CHIBIOS_INCLUDE_DIRS}"
    "${BRAINFPV_DIR}"
    "${CHIBIOS_F4_INCLUDE_DIRS}"
)

set(BRAINFPV_H7_INCLUDE_DIRS
    "${STM32H7_INCLUDE_DIRS}"
    "${CHIBIOS_INCLUDE_DIRS}"
    "${BRAINFPV_DIR}"
    "${CHIBIOS_H7_INCLUDE_DIRS}"
)

set(BRAINFPV_SRC
  "${MAIN_SRC_DIR}/main_chibios.c"
  "${MAIN_SRC_DIR}/cms/cms_menu_brainfpv.c"
  "${CHIBIOS_SRC}"
  "${BRAINFPV_INAV_SRC}"
)

set(BRAINFPV_F4_SRC
  "${BRAINFPV_SRC}"
  "${STM32F411_OR_F427_STDPERIPH_SRC}"
  "${STM32F4_STDPERIPH_SRC_DIR}/stm32f4xx_qspi.c"
  "${STM32F4_STDPERIPH_SRC_DIR}/stm32f4xx_rcc.c" 
  "${CHIBIOS_SRC}"
  "${CHIBIOS_F4_HAL_SRC}"
)

set(BRAINFPV_H7_SRC
  "${BRAINFPV_SRC}"
  "${STM32H7_HAL_SRC}" 
  "${STM32H7_SRC}"
  "${STM32H7_HAL_DIR}/Src/stm32h7xx_hal_mdma.c"
  "${STM32H7_HAL_DIR}/Src/stm32h7xx_hal_comp.c"
  "${CHIBIOS_SRC}"
  "${CHIBIOS_H7_HAL_SRC}"
)

set(STM32F446_BRAINFPV_COMPILE_DEFINITIONS
    STM32F446xx
    MCU_FLASH_SIZE=512
    USE_CHIBIOS
    CORTEX_USE_FPU=TRUE
    CORTEX_SIMPLIFIED_PRIORITY=TRUE
)

set(STM32H750_BRAINFPV_COMPILE_DEFINITIONS
    ${STM32H7_DEFINITIONS}
    STM32H7
    STM32H750xx
    #STM32H743xx
    #STM32H743xi
    MCU_FLASH_SIZE=1024
    USE_CHIBIOS
    CORTEX_USE_FPU=TRUE
    CORTEX_SIMPLIFIED_PRIORITY=TRUE
)

function(target_brainfpv_stm32f446 name)
    target_stm32f4xx(
        NAME ${name}
        HSE_MHZ 16
        DISABLE_MSC
        STARTUP startup_chibios_stm32f446xx.s
        SOURCES ${BRAINFPV_F4_SRC}
        INCLUDE_DIRECTORIES ${BRAINFPV_F4_INCLUDE_DIRS}
        COMPILE_DEFINITIONS ${STM32F446_BRAINFPV_COMPILE_DEFINITIONS}
        LINKER_SCRIPT stm32_flash_f446_chibios
        SVD STM32F446
        ${ARGN}
    )
endfunction()

function(target_brainfpv_stm32h750 name)
    target_stm32(
        NAME ${name}
        HSE_MHZ 16
        STARTUP startup_stm32h743xx.s
        SOURCES ${BRAINFPV_H7_SRC}
        COMPILE_DEFINITIONS ${STM32H750_BRAINFPV_COMPILE_DEFINITIONS}
        COMPILE_OPTIONS ${CORTEX_M7_COMMON_OPTIONS} ${CORTEX_M7_COMPILE_OPTIONS}
        INCLUDE_DIRECTORIES ${BRAINFPV_H7_INCLUDE_DIRS}
        
        MSC_SOURCES ${STM32H7_USBMSC_SRC} ${STM32H7_MSC_SRC}
        VCP_SOURCES ${STM32H7_USB_SRC} ${STM32H7_VCP_SRC}
        VCP_INCLUDE_DIRECTORIES ${STM32H7_USB_INCLUDE_DIRS} ${STM32H7_VCP_DIR}

        OPTIMIZATION -O2

        OPENOCD_TARGET stm32h7x

        DISABLE_MSC # This should be temporary
        
        LINKER_SCRIPT stm32_flash_h743xi
        SVD STM32F446
        ${ARGN}
    )
endfunction()


SET(ASM_OPTIONS "-x assembler-with-cpp")


set(CMAKE_ASM_FLAGS_DEBUG "${CMAKE_ASM_FLAGS_DEBUG} ${ASM_OPTIONS}")
set(CMAKE_ASM_FLAGS_RELEASE "${CMAKE_ASM_FLAGS_RELEASE} ${ASM_OPTIONS}")
set(CMAKE_ASM_FLAGS_RELWITHDEBINFO "${CMAKE_ASM_FLAGS_RELWITHDEBINFO} ${ASM_OPTIONS}")
